version: "3.8"

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=BookDB
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgres
  app:
    depends_on:
      - postgresdb
    build: ./
    restart: on-failure
    env_file: ./.env
    ports:
      - 8080:8080
    environment:
        SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresdb:5432/BookDB"
        SPRING_DATASOURCE_USERNAME: "postgres"
        SPRING_DATASOURCE_PASSWORD: "12345"
        SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: