version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: Book
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  your_app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/Book
    ports:
      - "8090:8090"
