version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: Book
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678

  your_app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:12345678@postgres:5566/Book
    ports:
      - "8090:8090"